
name: node build

on: 
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run build
    - run: npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
    - run: npm run publish